// InsPackage/src/components/show/monitor.vue
<script setup lang="ts">
//显示器
//https://systeminformation.io/graphics.html
import { computed } from "vue";
import deviceData from "@/components/state/data";
import { judge_bool } from "@/components/state/tool";
const data = computed(() => {
  return deviceData.value.graphics;
});

const formattedData = data.value.displays.map((data: any) => [
  { label: "供应商", value: data.vendor },
  { label: "供应商编号", value: data.vendorId },
  { label: "型号", value: data.model },
  { label: "生产年份", value: data.productionYear },
  { label: "序列号", value: data.serial },
  { label: "显示ID", value: data.displayId },
  { label: "主显示器", value: judge_bool(data.main) },
  { label: "内置显示器", value: judge_bool(data.builtin) },
  { label: "链接类型", value: data.connection },
  { label: "尺寸", value: `${data.sizeX} x ${data.sizeY} 毫米` },
  { label: "颜色深度（位）", value: `${data.pixelDepth} 位` },
  { label: "分辨率", value: `${data.resolutionX} x ${data.resolutionY} 像素` },
  {
    label: "当前像素水平",
    value: `${data.currentResX} x ${data.currentResY} 像素`,
  },
  { label: "位置", value: `(${data.positionX}, ${data.positionY})` },
  { label: "刷新率", value: `${data.currentRefreshRate} 赫兹` },
  { label: "设备名称", value: data.deviceName },
]);
</script>
<template>
  <div class="details">
    <template v-for="(item, index) in formattedData" :key="item.label">
      <h3>显示器{{ index + 1 }}</h3>
      <ul>
        <template v-for="list in item" :key="list.value">
          <li v-if="list.value && list.value !== ''">
            <span>{{ list.label }}</span>
            <span>{{ list.value }}</span>
          </li>
        </template>
      </ul>
    </template>
  </div>
</template>
<style scoped lang="less"></style>

// search/src/components/part/device-details/detailed/show/monitor.tsx
/**
 * 设备详情 - 显示器
 * https://systeminformation.io/graphics.html
 */
import { Table } from "antd";
import { ComputerDishplays } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
import { judge_bool } from "@/store/tool";
interface Props {
  data: ComputerDishplays[];
}
const App: React.FC<Props> = ({ data }) => {

  const formattedData = (item: ComputerDishplays) => {
    const arr = [
      { key: "1", label: "型号", value: item.model },
      { key: "2", label: "生产年份", value: item.productionYear },
      {
        key: "3",
        label: "分辨率",
        value: `${item.resolutionX} x ${item.resolutionY} 像素`,
      },
      {
        key: "4",
        label: "当前像素水平",
        value: `${item.currentResX} x ${item.currentResY} 像素`,
      },
      { key: "5", label: "刷新率", value: `${item.currentRefreshRate} 赫兹` },
      { key: "6", label: "主显示器", value: judge_bool(item.main) },
      { key: "7", label: "内置显示器", value: judge_bool(item.builtin) },
      { key: "8", label: "供应商", value: item.vendor },
      { key: "9", label: "供应商编号", value: item.vendorId },

      { key: "10", label: "显示ID", value: item.displayId },

      { key: "11", label: "链接类型", value: item.connection },
      { key: "12", label: "尺寸", value: `${item.sizeX} x ${item.sizeY} 毫米` },
      { key: "13", label: "颜色深度（位）", value: `${item.pixelDepth} 位` },

      {
        key: "14",
        label: "位置",
        value: `(${item.positionX}, ${item.positionY})`,
      },

      { key: "15", label: "设备名称", value: item.deviceName },
      { key: "16", label: "序列号", value: item.serial },
    ];
    return arr;
  };

  return (
    <>
      {data.map((item, index) => {
        return (
          <div key={index}>
            <p className="font-black my-2 text-xl">显示器 - {index + 1}</p>
            <Table dataSource={formattedData(item)} columns={columnsTable} />
          </div>
        );
      })}
    </>
  );
};

export default App;
