// vite/src/components/block/detailed/show/bios.tsx
/**
 * 设备详情 - BIOS
 * https://systeminformation.io/system.html
 */
import { Table } from "antd";
import { ComputerBios } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
interface Props {
  data: ComputerBios;
}
const App: React.FC<Props> = ({ data }) => {
  console.log("CPU");
  console.log(data);
  // CPU信息的数组
  const cpuItems = [
    { key: "1",label: "供应商", value: data.vendor },
    { key: "2",label: "版本", value: data.version },
    { key: "3",label: "发布日期", value: data.releaseDate },
    { key: "4",label: "校订", value: data.revision },
    { key: "5",label: "语言", value: data.langage },
    { key: "6",label: "特征", value: data.features },
    { key: "7",label: "序列号", value: data.serial },

    
  ];

  return (
    <>
      <Table dataSource={cpuItems} columns={columnsTable} />
    </>
  );
};

export default App;

// InsPackage/src/components/show/bios.vue
<script setup lang="ts">
import { computed } from "vue";
import deviceData from "@/components/state/data";

const data = computed(() => {
  return deviceData.value.bios;
});

// BIOS 信息的数组
const biosItems = [
  { label: "供应商", value: data.value.vendor },
  { label: "版本", value: data.value.version },
  { label: "发布日期", value: data.value.releaseDate },
  { label: "校订", value: data.value.revision },
  { label: "语言", value: data.value.langage },
  { label: "特征", value: data.value.features },
  { label: "序列号", value: data.value.serial },
  
];
</script>

<template>
  <div class="details">
    <h2>BIOS</h2>
    <ul>
      <template v-for="item in biosItems" :key="item.label">
        <li v-if="item.value && item.value !== ''">
          <span>{{ item.label }}</span>
          <span>{{ item.value }}</span>
        </li>
      </template>
    </ul>
  </div>
</template>

<style scoped lang="less"></style>
