// vite/src/components/block/detailed/show/cpu.tsx
/**
 * 设备详情 - CPU
 * https://systeminformation.io/cpu.html
 */
import { Table } from "antd";
import { ComputerCpu } from "@/store/interface";
import { bytesToMB, judge_bool } from "@/store/tool";
import { columnsTable } from "@/store/dataReplace";
interface Props {
  data: ComputerCpu;
}
const App: React.FC<Props> = ({ data }) => {
  console.log("CPU");
  console.log(data);
  // CPU信息的数组
  const Items = [
    { key: "1", label: "制造者", value: data.manufacturer },
    { key: "2", label: "品牌", value: data.brand },
    { key: "3", label: "速度", value: data.speed },
    { key: "4", label: "速度最小值", value: data.speedMin },
    { key: "5", label: "速度最大值", value: data.speedMax },
    { key: "6", label: "总督", value: data.governor },
    { key: "7", label: "核心", value: data.cores },
    { key: "8", label: "物理核心", value: data.physicalCores },
    { key: "9", label: "性能核心", value: data.performanceCores },
    { key: "10", label: "效率核心", value: data.efficiencyCores },
    { key: "11", label: "处理器", value: data.processors },
    { key: "12", label: "插座类型", value: data.socket },
    { key: "13", label: "供应商", value: data.vendor },
    { key: "14", label: "系列", value: data.family },
    { key: "15", label: "型号", value: data.model },
    { key: "16", label: "步进", value: data.stepping },
    { key: "17", label: "校订", value: data.revision },
    { key: "18", label: "电压", value: data.voltage },
    { key: "19", label: "处理器标志", value: data.flags },
    { key: "20", label: "虚拟化", value: judge_bool(data.virtualization) },
    { key: "21", label: "L1数据", value: bytesToMB(data.cache.l1d, "MB") },
    { key: "22", label: "L1指令", value: bytesToMB(data.cache.l1i, "MB") },
    { key: "23", label: "L2缓存", value: bytesToMB(data.cache.l2, "MB") },
    { key: "24", label: "L3缓存", value: bytesToMB(data.cache.l3, "MB") },
  ];

  return (
    <>
      <Table dataSource={Items} columns={columnsTable} />
    </>
  );
};

export default App;

// InsPackage/src/components/show/cpu.vue
<script setup lang="ts">
//https://systeminformation.io/cpu.html
import { computed } from "vue";
import deviceData from "@/components/state/data";
import { formatBytes, judge_bool } from "@/components/state/tool";

const data = computed(() => {
  return deviceData.value.cpu;
});

const cacheLabels = {
  l1d: "L1数据",
  l1i: "L1指令",
  l2: "L2缓存",
  l3: "L3缓存",
};

// CPU信息的数组
const cpuItems = [
  { label: "制造者", value: data.value.manufacturer },
  { label: "品牌", value: data.value.brand },
  { label: "速度", value: data.value.speed },
  { label: "速度最小值", value: data.value.speedMin },
  { label: "速度最大值", value: data.value.speedMax },
  { label: "总督", value: data.value.governor },
  { label: "核心", value: data.value.cores },
  { label: "物理核心", value: data.value.physicalCores },
  { label: "性能核心", value: data.value.performanceCores },
  { label: "效率核心", value: data.value.efficiencyCores },
  { label: "处理器", value: data.value.processors },
  { label: "插座类型", value: data.value.socket },
  { label: "供应商", value: data.value.vendor },
  { label: "系列", value: data.value.family },
  { label: "型号", value: data.value.model },
  { label: "步进", value: data.value.stepping },
  { label: "校订", value: data.value.revision },
  { label: "电压", value: data.value.voltage },
  { label: "处理器标志", value: data.value.flags },
  { label: "虚拟化", value: judge_bool(data.value.virtualization) },
];

// CPU缓存信息的数组
const cacheItems = Object.entries(data.value.cache).map(([key, value]) => {
  return {
    label: cacheLabels[key],
    value: formatBytes(value),
  };
});
</script>

<template>
  <div class="details">
    <h2>CPU</h2>
    <ul>
      <template v-for="item in cpuItems" :key="item.label">
        <li v-if="item.value && item.value !== ''">
          <span>{{ item.label }}</span>
          <span>{{ item.value }}</span>
        </li>
      </template>

      <template v-for="item in cacheItems" :key="item.label">
        <li v-if="item.value && item.value !== ''">
          <span>{{ item.label }}</span>
          <span>{{ item.value }}</span>
        </li>
      </template>
    </ul>
  </div>
</template>

<style scoped lang="less"></style>
