// vite/src/components/part/device-details/detailed/show/uuid.tsx
/**
 * 设备详情 - UUID
 *
 */
import { Table } from "antd";
import { ComputerUuid } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
interface Props {
  data: ComputerUuid;
}
const App: React.FC<Props> = ({ data }) => {
  

  const Items = [
    { key: "1", label: "系统", value: data.os },
    { key: "2", label: "硬件", value: data.hardware },
  ];

  return (
    <>
      <Table dataSource={Items} columns={columnsTable} />
    </>
  );
};

export default App;

// InsPackage/src/components/show/uuid.vue
<script setup lang="ts">
//UUID
import { computed } from "vue";
import deviceData from "@/components/state/data";

const data = computed(() => {
  return deviceData.value.uuid;
});

// 机箱信息的数组
const chassisItems = [
  { label: "系统", value: data.value.os },
  { label: "硬件", value: data.value.hardware },
];
</script>

<template>
  <div class="details">
    <h2>机箱</h2>
    <ul>
      <template v-for="item in chassisItems" :key="item.label">
        <li v-if="item.value && item.value !== ''">
          <span>{{ item.label }}</span>
          <span>{{ item.value }}</span>
        </li>
      </template>
    </ul>
    <ul v-for="(item, index) in data.macs" :key="index">
      <li>
        <span>网口 - {{ index }}</span
        ><span>{{ item }}</span>
      </li>
    </ul>
  </div>
</template>

<style scoped lang="less"></style>
