// vite/src/components/block/detailed/show/disk.tsx
/**
 * 设备详情 - 硬盘
 */
import { Table } from "antd";
import { ComputerDevice } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
import { bytesToMB } from "@/store/tool";
interface Props {
  data: ComputerDevice[];
}
const App: React.FC<Props> = ({ data }) => {
  const formattedData = (item: ComputerDevice) => {
    const arr = [
      { key: "1", label: "设备", value: item.device },
      { key: "2", label: "类型", value: item.type },
      { key: "3", label: "名称", value: item.name },
      { key: "4", label: "供应商", value: item.vendor },
      { key: "5", label: "容量", value: bytesToMB(item.size, "GB") },
      { key: "6", label: "总气缸数", value: item.totalCylinders },
      { key: "7", label: "总头数", value: item.totalHeads },
      { key: "8", label: "总曲目数", value: item.totalTracks },
      { key: "9", label: "总扇区", value: item.totalSectors },
      { key: "10", label: "每缸轨道数", value: item.tracksPerCylinder },
      { key: "11", label: "每轨扇区数", value: item.sectorsPerTrack },
      { key: "12", label: "每个扇区字节数", value: item.bytesPerSector },
      { key: "13", label: "固件修订版本", value: item.firmwareRevision },
      { key: "14", label: "序列号", value: item.serialNum },
      { key: "15", label: "接口类型", value: item.interfaceType },
      { key: "16", label: "智能状态", value: item.smartStatus },
      { key: "17", label: "温度", value: item.temperature },
      { key: "18", label: "智能数据", value: item.smartData },
    ];
    return arr;
  };

  return (
    <>
      {data.map((item, index) => {
        return (
          <>
            <div key={index}>
              <p className="font-black my-2 text-xl">硬盘 - {index+1}</p>
              <Table dataSource={formattedData(item)} columns={columnsTable} />
            </div>
          </>
        );
      })}
    </>
  );
};

export default App;

// vite/src/components/block/detailed/show/disk.vue
<script setup lang="ts">
// 硬盘 - 已检查
// https://systeminformation.io/filesystem.html
import { computed } from "vue";
import deviceData from "@/components/state/data";
import { formatBytes } from "@/components/state/tool";

const data = computed(() => deviceData.value.diskLayout);

const formattedData = data.value.map((data: any) => [
  { label: "设备", value: data.device },
  { label: "类型", value: data.type },
  { label: "名称", value: data.name },
  { label: "供应商", value: data.vendor },
  { label: "容量", value: formatBytes(data.size, "g") },
  { label: "总气缸数", value: data.totalCylinders },
  { label: "总头数", value: data.totalHeads },
  { label: "总曲目数", value: data.totalTracks },
  { label: "总扇区", value: data.totalSectors },
  { label: "每缸轨道数", value: data.tracksPerCylinder },
  { label: "每轨扇区数", value: data.sectorsPerTrack },
  { label: "每个扇区字节数", value: data.bytesPerSector },
  { label: "固件修订版本", value: data.firmwareRevision },
  { label: "序列号", value: data.serialNum },
  { label: "接口类型", value: data.interfaceType },
  { label: "智能状态", value: data.smartStatus },
  { label: "温度", value: data.temperature },
  { label: "智能数据", value: data.smartData },
]);
</script>

<template>
  <div class="details">
    <h2>硬盘</h2>
    <template v-for="(item, index) in formattedData" :key="item.label">
      <h3>硬盘{{ index + 1 }}</h3>
      <ul>
        <template v-for="list in item" :key="list.value">
          <li v-if="list.value && list.value !== ''">
            <span>{{ list.label }}</span>
            <span>{{ list.value }}</span>
          </li>
        </template>
      </ul>
    </template>
  </div>
</template>

<style scoped lang="less"></style>
