// vite/src/components/block/detailed/show/memory.vue
<script setup lang="ts">
//内存
//https://systeminformation.io/memory.html
import {  computed } from "vue";
import deviceData from "@/components/state/data";
import { formatBytes, judge_bool } from "@/components/state/tool";

const data = computed(() => {
  return deviceData.value.memLayout;
});

const formattedData = data.value.map((data:any) => [
  { label: "大小", value: formatBytes(data.size, "g") },
  { label: "内存库", value: data.bank },
  { label: "内存类型", value: data.type },
  { label: "ECC内存", value: judge_bool(data.ecc) },
  { label: "时钟速度", value: data.clockSpeed },
  { label: "外形尺寸", value: data.formFactor },
  { label: "制造者", value: data.manufacturer },
  { label: "部件号", value: data.partNum },
  { label: "序号", value: data.serialNum },
  { label: "电压已配置", value: data.voltageConfigured },
  { label: "最小电压", value: data.voltageMin },
  { label: "最大电压", value: data.voltageMax },
]);
</script>
<template>
  <div class="details">
    <h2>内存</h2>
    <template v-for="(item, index) in formattedData" :key="item.label">
      <h3>内存条{{ index + 1 }}</h3>
      <ul>
        <template v-for="list in item" :key="list.value">
          <li v-if="list.value && list.value !== ''">
            <span>{{ list.label }}</span>
            <span>{{ list.value }}</span>
          </li>
        </template>
      </ul>
    </template>
  </div>
</template>
<style scoped lang="less"></style>

// vite/src/components/block/detailed/show/memory.tsx
/**
 * 设备详情 - 内存
 * https://systeminformation.io/memory.html
 */
import { Table } from "antd";
import { ComputerRam } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
import { bytesToMB,judge_bool } from "@/store/tool";
interface Props {
  data: ComputerRam[];
}
const App: React.FC<Props> = ({ data }) => {
  console.log("内存");
  console.log(data);
  const formattedData = (item: ComputerRam) => {
    const arr = [
      { key: "1", label: "大小", value: bytesToMB(item.size, "GB") },
      { key: "2", label: "内存库", value: item.bank },
      { key: "3", label: "内存类型", value: item.type },
      { key: "4", label: "ECC内存", value: judge_bool(item.ecc) },
      { key: "5", label: "时钟速度", value: item.clockSpeed },
      { key: "6", label: "外形尺寸", value: item.formFactor },
      { key: "7", label: "制造者", value: item.manufacturer },
      { key: "8", label: "部件号", value: item.partNum },
      { key: "9", label: "序号", value: item.serialNum },
      { key: "10", label: "电压已配置", value: item.voltageConfigured },
      { key: "11", label: "最小电压", value: item.voltageMin },
      { key: "12", label: "最大电压", value: item.voltageMax },
    ];
    return arr;
  };

  return (
    <>
      {data.map((item, index) => {
        return (
          
            <div key={index}>
              <p className="font-black my-2 text-xl">内存 - {index+1}</p>
              <Table dataSource={formattedData(item)} columns={columnsTable} />
            </div>
          
        );
      })}
    </>
  );
};

export default App;
