// vite/src/components/block/detailed/show/net.vue
<script setup lang="ts">
//NET
//https://systeminformation.io/network.html
import { computed } from "vue";
import deviceData from "@/components/state/data";
import { judge_bool } from "@/components/state/tool";
const data = computed(() => {
  return deviceData.value.net;
});

const formattedData = data.value.map((data: any) => [
  { label: "接口名", value: data.ifaceName },
  { label: "默认接口", value: judge_bool(data.default) },
  { label: "IPV4", value: data.ip4 },
  { label: "IPV4子网掩码", value: data.ip4subnet },
  { label: "IPV6", value: data.ip6 },
  { label: "IPV6子网掩码", value: data.ip6subnet },
  { label: "MAC地址", value: data.mac },
  { label: "内部接口", value: judge_bool(data.internal) },
  { label: "虚拟接口", value: judge_bool(data.virtual) },
  { label: "操作状态", value: judge_bool(data.operstate) },
  { label: "类型", value: data.type },
  { label: "双工", value: data.duplex },
  { label: "MTU最大传输单元", value: data.mtu },
  { label: "速度", value: data.speed },
  { label: "通过DHCP获取的地址", value: judge_bool(data.dhcp) },
  { label: "DNS后缀", value: data.dnsSuffix },
  { label: "IEEE 802.1x身份验证", value: data.ieee8021xAuth },
  { label: "IEEE 802.1x状态", value: data.ieee8021xState },
  { label: "运营商变更", value: data.carrierChanges },
]);
</script>
<template>
  <div class="details">
    <template v-for="(item, index) in formattedData" :key="item.label">
      <h3>网卡 - {{ index + 1 }}</h3>
      <ul>
        <template v-for="list in item" :key="list.value">
          <li v-if="list.value && list.value !== ''">
            <span>{{ list.label }}</span>
            <span>{{ list.value }}</span>
          </li>
        </template>
      </ul>
    </template>
  </div>
</template>

// admin-vite/src/components/part/device-details/detailed/show/net.tsx
/**
 * 设备详情 - 网卡
 * https://systeminformation.io/network.html
 */
import { Table } from "antd";
import { ComputerNet } from "@/store/interface";
import { columnsTable } from "@/store/dataReplace";
import { judge_bool, removeEmpty } from "@/store/tool";
interface Props {
  data: ComputerNet[];
}
const App: React.FC<Props> = ({ data }) => {

  const formattedData = (item: ComputerNet) => {
    const arr = [
      { key: "1", label: "接口名", value: item.ifaceName },
      { key: "2", label: "默认接口", value: judge_bool(item.default) },
      { key: "3", label: "速度", value: item.speed },
      { key: "4", label: "类型", value: item.type },
      { key: "5", label: "IPV4", value: item.ip4 },
      { key: "6", label: "IPV4子网掩码", value: item.ip4subnet },
      { key: "7", label: "IPV6", value: item.ip6 },
      { key: "8", label: "IPV6子网掩码", value: item.ip6subnet },
      { key: "9", label: "MAC地址", value: item.mac },
      { key: "10", label: "内部接口", value: judge_bool(item.internal) },
      { key: "11", label: "虚拟接口", value: judge_bool(item.virtual) },
      { key: "12", label: "操作状态", value: judge_bool(item.operstate) },
      { key: "13", label: "双工", value: item.duplex },
      { key: "14", label: "MTU最大传输单元", value: item.mtu },
      { key: "15", label: "通过DHCP获取的地址", value: judge_bool(item.dhcp) },
      { key: "16", label: "DNS后缀", value: item.dnsSuffix },
      { key: "17", label: "IEEE 802.1x身份验证", value: item.ieee8021xAuth },
      { key: "18", label: "IEEE 802.1x状态", value: item.ieee8021xState },
      { key: "19", label: "运营商变更", value: item.carrierChanges },
    ];
    return removeEmpty(arr);
  };

  return (
    <>
      {data.map((item, index) => {
        return (
          <div key={index}>
            <p className="font-black my-2 text-xl">网卡 - {index + 1}</p>
            <Table dataSource={formattedData(item)} columns={columnsTable} />
          </div>
        );
      })}
    </>
  );
};

export default App;
